feat: split apk files
revanced/revanced-patcher pull request #113
Opened 2022-09-30 04:05 UTC by oSumAtrIX

## About

This PR adds support for split apks. The API usage can be seen on the implementing CLI branch: https://github.com/revanced/revanced-cli/tree/feat/split

## TODO

- [ ] Tests
- [ ] Consider all temporal paths in `ResourceData`

2022-09-30 10:10 UTC, Sculas requested changes

2022-09-30 10:10 UTC, Sculas commented on src/test/kotlin/app/revanced/patcher/usage/resource/patch/ExampleResourcePatch.kt
> +        data
```suggestion
```

2022-09-30 13:54 UTC, oSumAtrIX commented
@Sculas the problem with just generically detecting whether it is a split or not is, that after patching it is required to know which apk is what, the language, assets or other apks. Now one might say, why not supply one apk each to the patcher, the problem with that is, that a patch would not be able to access all apks at the same time, like it does currently with a full apk, which is why I went with a sealed Apk class and a defined set of Subclasses for the splits.

2022-09-30 15:08 UTC, Sculas commented
I understand, but all Java code is only ever in the base APK. All other splits do not contain dex files. So the problem you're trying to solve never existed to begin with.

2022-09-30 15:19 UTC, Sculas commented
Either way, if this implementation works then it's good enough. Improvements can be made with time.

2022-12-02 19:07 UTC, bao000 reviewed
<dependency>
  <groupId>app.revanced</groupId>
  <artifactId>revanced-patcher</artifactId>
  <version>6.3.0</version>
</dependency>

2023-05-16 03:49 UTC, oSumAtrIX commented
Superseded by #165.

2023-05-16 03:49 UTC, closed without merging