refactor!: cleanup patch options
revanced/revanced-patcher pull request #123
Opened 2022-11-13 21:06 UTC by Sculas

This PR cleans up the patch options system to only what's needed, simplifies it a lot, and improves it overall.
Things have been moved into their respective package as well, so this is a breaking change.

This PR also includes a small general interface for serialization, but it can be removed if requested.

2022-11-14 14:18 UTC, Sculas commented on src/main/kotlin/app/revanced/patcher/patch/options/OptionsContainer.kt
> +    protected fun stringPreference(
@oSumAtrIX What naming do you prefer?
`stringPreference` or `stringOption`?

2022-12-02 01:40 UTC, oSumAtrIX requested changes

2022-12-02 01:42 UTC, closed without merging

2022-12-02 01:42 UTC, oSumAtrIX commented
Why has this been closed?

2022-12-02 01:43 UTC, Sculas commented
Forgot I had this PR open, so I closed it since I don't have motivation to work on this PR right now (working on other things).