fix(extensions): Fix off-by-one in removeInstructions
revanced/revanced-patcher pull request #167
Opened 2023-05-04 16:53 UTC by rstular

2023-05-05 21:45 UTC, oSumAtrIX requested changes

2023-05-05 21:45 UTC, oSumAtrIX commented on src/main/kotlin/app/revanced/patcher/extensions/Extensions.kt
> +    for (i in (0 until count).reversed()) {
Why not just:
```suggestion
    for (i in count - 1 downTo 0) {
```

2023-05-05 23:59 UTC, Sculas commented
@oSumAtrIX Should be reopened as well.

2023-05-06 11:25 UTC, Sculas approved these changes

2023-05-06 11:42 UTC, merged